pipeline {
    agent any

 environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages{

      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

      stage('Checkout SCM') {
         steps{
            git branch: 'main', url: 'https://github.com/RazaqAdedeji/ansible-config-mgt.git'
         }
       }
      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'          
        }
     }


      stage('Run Ansible') {
        steps {
            ansiblePlaybook become: true, credentialsId: '7845ee4a-7727-4bf2-9154-33e1833bc25a', disableHostKeyChecking: true, installation: 'ansible', inventory: '${inventory}', playbook: 'playbooks/site.yml'
        }
      }

      stage('Clean Workspace after build'){
        steps{
          cleanWs()
        }
      }
   }
}