- name: Include dynamic variables 
  hosts: all
  tasks:
    - import_playbook: ../static-assignments/common.yml 
    - import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
  name: Webserver assignment
  tasks:
    - import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  tasks:
    - import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
